name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version: [ '1.24.x' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dm tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y cryptsetup dmsetup
          sudo modprobe dm-mod
          sudo modprobe dm-zero
          sudo modprobe dm-verity

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: sudo make && sudo make install

      - name: Run unit tests (race)
        run: sudo -E go test -v -race ./...

      - name: Run integration tests
        run: sudo -E bash tests/verity-compat.sh

  golangci:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=5m
